### ISSUE TITLE
Introducing forcats

### ISSUE THREAD

**Issue by oscci** [moderndive/moderndive_book#103]
Re this section:
_You can manually specify which continent to use as baseline instead of the default choice of whichever comes first alphabetically, but we leave that to a more advanced course. (The forcats package is particularly nice for doing this and we encourage you to explore using it.)_  
It is great to learn about forcats: I seem to remember stumbling on it after a very frustrating experience of trying to reorder levels of a factor. While I can see that you don't want to digress too much from explaining about regression, I wonder if it would not be worth saying a bit more about R's default behaviour with factor levels, as I think many people get stuck on this when they come to analyse their own data.

**Comment by rudeboybert** [comment]
That was an editorial decision on our part. On the one hand, we'd love to be able to include situations like this one, but on the other (as you suggest about the digression) once we try to start including everything, soon we'll end up with nothing. It's a tough balancing act. Also, in our opinions the reordering of factors is more of a topic for a straight data science course, and not so much a course on statistical inference that uses data science. 

However, as you suggest, it might be worth at least point readers in the right direction, without entirely opening the can of worms that is categorical/factors.

**Comment by rudeboybert** [comment]
Hi @oscci, thanks for this suggestion. We just addressed it in d7dc2ab497bb95395123bd83af007b6e70579e7a

Specifically in Section [6.2.2 Linear regression](https://moderndive.netlify.com/6-regression.html#model2table) on linear regression with a categorical variable we amended the text to read:

> You might be asking at this point why was Africa chosen as the "baseline for comparison" group. For no other reason than it comes first alphabetically of the five continents; by default R arranges factors/categorical variables in alphanumeric order. However you can change this baseline group to be another continent if you manipulate the variable `continent`'s factor "levels" using the `forcats` package. See [Chapter 15](https://r4ds.had.co.nz/factors.html) of Garrett Grolemund and Hadley Wickham's book for examples.
