### ISSUE TITLE
section 9.4 

### ISSUE THREAD

**Issue by oscci** [moderndive/moderndive_book#105]
Suggestion: when comparing histograms for bootstrap and sampling distributions, would be better if one could be superimposed on the other: or at least have them shown side by side. Currently have to scroll up and down to compare them.

**Comment by rudeboybert** [comment]
Thanks for comment! We'll incorporate in Chap 8-11 changes in #95

**Comment by rudeboybert** [comment]
Hey @oscci, we did this in pull request #149, specifically in Section "9.7.1 Comparing bootstrap and sampling distributions" [Figure 9.28](https://moderndive.netlify.com/9-confidence-intervals.html#fig:side-by-side) where we emphasize the center of the bootstrap distribution is the dashed line.

<img width="786" alt="sampling_vs_bootstrap" src="https://user-images.githubusercontent.com/4574203/60440072-ff056000-9be1-11e9-954b-c987da0cec3a.png">

While they aren't superimposed, they are stacked right on top of each other making them easy to compare. It only occurred to us after the fact that this way it really brings home the point that the bootstrap really can't improve you estimates, but only rather only get a good estimate of the spread/SE!

Thanks again for the great suggestion!
