### ISSUE TITLE
GitHub/Publishing

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/moderndive_book#12]
**New desiderata**:
* Transfer ownership of repo from <https://github.com/ismayc/moderndiver-book> to ModernDive GitHub organization <https://github.com/moderndive/>
* From there have
    + main branch be source code for latest released version
    + devel branch for source code for the development version
* Deploy/host the different versions of ModernDive via netlify as follows:
    + Have release version at moderndive.com deployed via netlify instead of HostGator as per this [tweet](https://twitter.com/juliasilge/status/941482834685857793)
    + Development version at <http://moderndive.netlify.com>
    + Past versions output/source code at moderndive.github.io/<old_version>
* Fix bookdown.org ModernDive cover issue due to https on HostGator

**Originally stated action items**: Use travis deployment instead of manual builds for both ModernDive.com and
* Could use the gh-pages branch of <http://github.com/ismayc/moderndiver-book> to publish the book to instead using travis
* This allows us to only have to change the Rmd files on GitHub.com and have the page automatically update
    + Currently this is done via travis on:  
    <http://github.com/ismayc/moderndiver-book> to create a new repo at 
     <http://github.com/ismayc/moderndive> that creates a book at 
    <http://ismayc.github.io/moderndive> and also at
    <http://moderndive.netlify.com>
    + There’s no need to push to a new repo though (could just as easily push to gh-pages on moderndiver-book instead)
    + This is the process I did with <http://ismayc.github.io/chemistr-book>
* Should also create a moderndive-releases GitHub repo that is updated only when we go to the next release
    + Then this repo could build via travis in the gh-pages branch and we could use netlify.com to come to populate ModernDive.com (also could get https support for free with netlify)

**Comment by ismayc** [comment]
[This](https://www.youtube.com/watch?v=Ybhb_tGnOsg) YouTube video should be helpful.

**Comment by rudeboybert** [comment]
* Custom domains: wow, easy-peasy. How do you want to manage the dev vs release on moderndive.com?
* You have repository creation permissions in the moderndive GitHub Org, so you should be able to transfer it.

**Comment by ismayc** [comment]
I think it does make sense to have `master` be the current "stable" release. It might make more sense for us to just convert the current `master` (whenever it is ready) to 0.3.0 instead of trying to put 0.2.0 that current lives on ModernDive.com into a repo as well. 

We can then use the `dev` branch to be where we make changes and improvements. The "live, on-the-fly" sorts of changes (where we don't build the `docs` folder can be pushed to `gh-pages` and then to moderndive.netlify.com, which is what I would probably share with your students). 

I don't think there is really a need for us to also deploy to https://moderndive.github.io/moderndiver-book, is there?

**Comment by ismayc** [comment]
Repo has been transferred! https://github.com/ismayc/moderndiver-book now redirects to https://github.com/moderndive/moderndiver-book

**Comment by ismayc** [comment]
Unfortunately the book itself doesn't transfer. https://moderndive.github.io/moderndiver-book/ works, but https://ismayc.github.io/moderndiver-book/ does not.

**Comment by ismayc** [comment]
For reference whenever we switch moderndive.com over later: https://www.edwinksl.com/blog/set-up-website-with-pelican-google-domains-and-netlify.html

**Comment by rudeboybert** [comment]
Maybe just put a README in https://ismayc.github.io/moderndiver-book/, like you say?

**Comment by ismayc** [comment]
Yeah, I think we should just have it be a webpage with a link to the new one and then update the README in `ismayc/moderndiver-book` to point to the new repo as well. We can do that when we meet up next.

**Comment by ismayc** [comment]
To clarify, this is what we are thinking when we move to 0.3.0 soon:

moderndive-dev.netlify.com comes from `gh-pages` which is populated from the `dev` branch on `moderndive/moderndive-book`. We could also set up moderndive.netlify.com to come from `docs` in the `master` branch on `moderndive/moderndive-book` which would then be sent to moderndive.org and then re-routed to moderndive.com via Google Domains.

**Comment by rudeboybert** [comment]
fancy!

**Comment by ismayc** [comment]
This is the modified workflow:

moderndive.netlify.com comes from gh-pages which is populated from the dev branch on moderndive/moderndive-book. We could also set up moderndive-release.netlify.com to come from `docs` in the master branch on moderndive/moderndive-book which would then be sent to moderndive.org and then re-routed to moderndive.com via Google Domains. moderndive.github.io/moderndive_book is from `master/docs` and is a backup to ModernDive.org (the stable version).

**Comment by rudeboybert** [comment]
@ismayc Is my understanding correct that the only outstanding element of this issue is cutting out HostGator from the modified workflow?

**Comment by ismayc** [comment]
@rudeboybert I believe so.
