### ISSUE TITLE
Add discussion of power into Chapter 10

### ISSUE THREAD

**Issue by acgerstein** [moderndive/moderndive_book#144]
This book is a phenomenal resource! I'm using parts of it for a workshop I'm giving to graduate students in microbiology. The students have had no formal prior instruction in statistics (or have forgotten everything they learned in a stat 1000 class years ago). 

Chapter 10 is an excellent introduction to the basics of hypothesis testing. For my purposes, the next logical thing to discuss after alpha and beta is power. I've pulled in relevant material from here: http://www.statisticsteacher.org/2017/09/15/what-is-power/ for the first iteration of my workshop, and suggest that a similar discussion would be at home in your book.

I tend to think that if I find something helpful others will  too, so thought I would pass these thoughts along to you. 

Again, thank you thank you thank you for developing this amazing resource.

**Comment by rudeboybert** [comment]
Hey @acgerstein, thanks for the kind words! And thanks for the suggestion on a discussion on power. We're currently pushing hard to get a draft in for our [first print edition](https://twitter.com/ModernDive/status/1102624954892406785). To be perfectly honest, we're not sure if we'll have enough time to add a new discussion on power (writing takes a long time). If you come across any code that creates visualizations that illustrate the ideas in the link you've shared, we'd definitely consider it!

On that same note we are currently in the midst of improving our Chapter 10 on Hypothesis Testing; you can see a [preview](https://moderndive.netlify.com/10-hypothesis-testing.html). The content is mostly the same, but we're reordering things a bit to present the ideas in what we feel is a more intuitive order for students with no formal prior instruction in statistics (or have forgotten) as you say!

Please let us know if you have any comments, and thanks for the suggestion! Much of how we decide what to include/not include in the book is based on user feedback like yours!

**Comment by rudeboybert** [comment]
Hi @acgerstein. Given our time frame, it's looking like we won't have time to write up a discussion on statistical power in the 1st print edition. Thanks for the suggestion nonetheless!

**Comment by acgerstein** [comment]
I completely understand - we are all capacity limited! I will be continuing to improve my workshop materials (which will be presented yearly). As I'm sure your book will see much success I expect there to be a second edition. If it is helpful for this future edition I would be happy to share the materials I develop if/when the time is right. My most sincere best regards.
