### ISSUE TITLE
Problem with photo for Figure 8.1

### ISSUE THREAD

**Issue by davidkane9** [moderndive/moderndive_book#151]
FIGURE 8.1: A bowl with red and white balls. 

But the photo shows a bowl with at least two blue (?) balls, in addition to the red and white ones.

**Comment by rudeboybert** [comment]
Hi David, thanks for noticing. We'll be updating the photos for this chapter before the next update.

**Comment by rudeboybert** [comment]
Hack fix in 0eb88d4d31960355d021b42fcb6940aae329a553. thanks
