### ISSUE TITLE
should be initial lower case on several Reference entries

### ISSUE THREAD

**Issue by davidkane9** [moderndive/moderndive_book#154]
———. 2015. Ggplot2movies: Movies Data. https://CRAN.R-project.org/package=ggplot2movies.

———. 2018. Nycflights13: Flights That Departed Nyc in 2013. https://CRAN.R-project.org/package=nycflights13.

should be ggplot2movies and nycflights13

**Comment by rudeboybert** [comment]
Thanks for this David! Since we don't cite any other of the many packages we use, it makes more sense to just remove the citations to these two packages. Done in b08801df4db72cae05df8b271c459483e98647e2
