### ISSUE TITLE
4.8.2 typo glimpse(flight_time)

### ISSUE THREAD

**Issue by jricoiii** [moderndive/moderndive_book#163]
flights_time_new <- flights %>% 
  select(contains("time")) %>% 
  rename(departure_time = dep_time,
         arrival_time = arr_time)
glimpse(flights_time)
-> returns an error

should be...

glimpse(flight_time_new)

**Comment by rudeboybert** [comment]
Thanks! Fixed in 1a6c3a33a9ae4ed911c8e7f54dafb9197ea002d0
