### ISSUE TITLE
4.2.2 pivot_wider

### ISSUE THREAD

**Issue by javi-s** [moderndive/ModernDive_book#222]
Hi, 

I noticed in chapter 4, section 4.2.2 (Converting to “tidy” data), when explaining pivot_longer, function pivot_wider is mentioned twiced.  I beleive it should mention pivot_longer instead.  Could this be an errata?

Thanks.

**Comment by rudeboybert** [comment]
Good catch! Fixed in f5196e1d1be1dc9952faeff09e28e5d582369953. thanks!

**Comment by javi-s** [comment]
You are welcome, thank you for the book!
