### ISSUE TITLE
Missing figure reference in Ch 9

### ISSUE THREAD

**Issue by javi-s** [moderndive/ModernDive_book#229]
Hi,

In Chapter 9, section 9.4.2, there appears to be an inccorrect reference to figure 9.16 in the development version at Netlify.

![image](https://user-images.githubusercontent.com/34216160/67668578-7cfb2d00-f970-11e9-9231-dcd14baac730.png)

Thanks.

**Comment by ismayc** [comment]
Thanks much! It was indeed an incorrect reference. It was fixed in [this commit](https://github.com/moderndive/ModernDive_book/commit/9ac411239235c84bb16bd7cf7b21e283cad2a8b7) and is now updated on moderndive.netlify.com.

**Comment by javi-s** [comment]
Thank you!!!
