### ISSUE TITLE
Inconsistency in Ch9?

### ISSUE THREAD

**Issue by javi-s** [moderndive/ModernDive_book#232]
Hi,

In Ch 9, as part of the case study at the end of section 9.5.3, in the development version at Netlify it reads:

> This  p-value is larger than our pre-specified  α significance level of 0.01. Thus, we are inclined to fail to reject the null hypothesis 

However, the p-value shown in the calculations right above appears to be smaller, 0.004, and it would lead to a different conclusion.

Thanks.

**Comment by ismayc** [comment]
Hmm, there is something strange going on here. In the published version on ModernDive.com, the p-value is greater than 0.01: https://moderndive.com/9-hypothesis-testing.html#ht-case-study. It’s probably best if we check why that is the case. Maybe the random seed is different?

I think it’s good for students to see both an example of rejecting H0 and failing to reject H0 at “usual” alpha thresholds.

**Comment by rudeboybert** [comment]
Ok, I'll engineer it so that the conclusion is the opposite of whatever the previous conclusion was.

Related sidenote: p-value based significance testing is ridiculous.

**Comment by ismayc** [comment]
This was fixed in the most recent commit to master. Thanks again for flagging!

**Comment by ismayc** [comment]
I lied. It's not quite ready just yet but should be soon!

**Comment by ismayc** [comment]
We shifted \alpha to be 0.001 since the `get_p_value()` function is now defined slightly differently than before.

**Comment by rudeboybert** [comment]
Now it's fixed! In #233

**Comment by ismayc** [comment]
Now updated: https://moderndive.netlify.com/9-hypothesis-testing.html

**Comment by javi-s** [comment]
Thank you for fixing!
