### ISSUE TITLE
Ch 11, axis label in figure

### ISSUE THREAD

**Issue by javi-s** [moderndive/ModernDive_book#243]
Hi,

In Chapter 11, section 11.2.2, the x axis of the figure showing number of births in US in 1999 is labeled "Data".  Wouldn’t the label read "Date" instead?

Thanks.

**Comment by rudeboybert** [comment]
Thanks @javi-s once again! Your thorough typo/error checking couldn't be coming at a better time! We're about to submit the final draft of our book for our print edition!

**Comment by javi-s** [comment]
Thank you ... looking forward to the print edition, I find the book really useful!
