### ISSUE TITLE
Add correspondence to DataCamp for flipped classrooms

### ISSUE THREAD

**Issue by higgi13425** [moderndive/moderndive_book#25]
This is likely to change with time,
and will need to be regularly updated, but

Roughly thinking:

Pre-course/ initial lab: Installing R and R Studio
    **based on** _Getting used to R, RStudio, and R Markdown_
       Read: R Packages: A Beginner's Guide _online_

MD 1& 2 = Working with the RStudio IDE parts 1/2,
                   Introduction to R, 
                   DataCamp Cheatsheets link,
                   Intermediate R
MD 3 = Introduction to the Tidyverse, 
           Data Vis w/ggplot part 1
MD4 = Introduction to Data, 
             Data Cleaning in R
MD5 =  Data Manipulation in R with Dplyr, 
             Joining Data in R with Dplyr
MD6 = Exploratory Data Analysis, 
        Intro to Stats: Correlation and Linear Regression, 
         Correlation and Regression?? (seems like pick one of b or c)
MD7 = Intro to Stats: Mult Regression, 
             Multiple &Logistic Regression
MD8 = Foundations of Inference
MD9 = Inference for Numerical Data
MD10 = ??
MD 11= Inference for Linear Regression
MD12 = Communicating with the Tidyverse,
             Reporting with R Markdown,
             Building Web Applications in R with Shiny

Also, Introduction to Data (MD4?), Correlation and Regression (MD6?) might fit in somewhere
Maybe more case studies?

**Comment by rudeboybert** [comment]
Hi @higgi13425, thanks for the suggestion. In the following [commit](https://github.com/moderndive/moderndive_book/pull/47/commits/3a0bd4dd216a4a53969de6a2904af7b41e883559) which is part of #47, I've added a non-exhaustive table in Chapter 1 of the correspondence of ModernDive chapters to DataCamp courses similar to the one below. Note:
- While there are definitely other existing DataCamp courses that are relevant, we didn't want to bloat this list to be too large
- Many of the listed DataCamp courses are still relatively new and this list is still somewhat in flux pending other new courses.  

| Chapter | Topic | DataCamp Courses   
| :-------------------------|:-------------------------|:-------------------------
| 2 | Basic R programming concepts | <a target="_blank" class="page-link" href="https://www.datacamp.com/courses/free-introduction-to-r">Introduction to R</a> and <a target="_blank" class="page-link" href="https://www.datacamp.com/courses/intermediate-r">Intermediate R</a>
| 3 & 5 | Introductory data visualization and wrangling | <a target="_blank" class="page-link" href="https://www.datacamp.com/courses/introduction-to-the-tidyverse">Introduction to the Tidyverse</a>
| 4 & 5 | Data "tidying" and intermediate data wrangling | <a target="_blank" class="page-link" href="https://www.datacamp.com/courses/working-with-data-in-the-tidyverse">Working with Data in the Tidyverse</a>
| 6 & 7 | Data modelling, basic regression, and multiple regression | <a target="_blank" class="page-link" href="https://www.datacamp.com/courses/modeling-with-data-in-the-tidyverse">Modeling with Data in the Tidyverse</a>
| 9 & 10 | Statistical inference: confidence intervals and hypothesis testing | <a target="_blank" class="page-link" href="https://www.datacamp.com/courses/inference-for-numerical-data">Inference for Numerical Data</a> and <a target="_blank" class="page-link" href="https://www.datacamp.com/courses/inference-for-categorical-data">Inference for Categorical Data</a>
| 11 | Inference for regression | <a target="_blank" class="page-link" href="https://www.datacamp.com/courses/inference-for-linear-regression">Inference for Regression</a>

**Comment by ismayc** [comment]
@higgi13425 Note that the [Foundations of Inference](https://www.datacamp.com/courses/foundations-of-inference) course is also being revamped to include the `infer` package so that it matches up with the other inference courses listed here. The [Introduction to Data](https://www.datacamp.com/courses/introduction-to-data) course also covers some relevant material to ModernDive as well.
