### ISSUE TITLE
suspicious link in chapter 5

### ISSUE THREAD

**Issue by xiaobitou** [moderndive/ModernDive_book#276]
The link "http://guessthecorrelation.com/" in chapter 5 is likely hacked.  It directs to a suspicious website.  Please consider removing it.

**Comment by ismayc** [comment]
Thanks for finding this! We've contacted the author of the page to see if they can fix it.

**Comment by xiaobitou** [comment]
> Thanks for finding this! We've contacted the author of the page to see if they can fix it.

Thank you!  Please note that chrome users who click on the link could find themselves receiving tons of unwanted pop-ups, as a result of unauthorized change in the "allowed" list in notification.

**Comment by rudeboybert** [comment]
Hi @xiaobitou, we contacted the http://guessthecorrelation.com/ site's owner, and it has been restored correctly. Thank you for bringing this to our attention.
