### ISSUE TITLE
object 'country' not found in 04-tidy.Rmd

### ISSUE THREAD

**Issue by Hendrik147** [moderndive/ModernDive_book#280]
Just to mention that the code is hanging at line 140, because 

Error in country %in% c("USA", "China", "Italy", "Saudi Arabia") : 
  object 'country' not found

**Comment by rudeboybert** [comment]
Hi @Hendrik147, you need to ensure that you pipe `drinks` from the `fivethirtyeight` package. It's working on my end:

``` r
library(tidyverse)
library(fivethirtyeight)

drinks %>% 
  filter(country %in% c("USA", "China", "Italy", "Saudi Arabia")) %>% 
  select(-total_litres_of_pure_alcohol)
#> # A tibble: 4 x 4
#>   country      beer_servings spirit_servings wine_servings
#>   <chr>                <int>           <int>         <int>
#> 1 China                   79             192             8
#> 2 Italy                   85              42           237
#> 3 Saudi Arabia             0               5             0
#> 4 USA                    249             158            84
```

<sup>Created on 2020-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Hendrik147** [comment]
Hi @rudeboybert,
just identified that the issue is a couple of lines before:
the drinks dataset needs to be specified as coming from FiveThirtyEight through:
fivethirtyeight::drinks

**Comment by rudeboybert** [comment]
Hi Hendrik, in MD we stick to the convention of always loading all necessary packages at the beginning of the chapter. Thanks for the comment nonetheless.
