### ISSUE TITLE
purl.Rout message after launching html rendering

### ISSUE THREAD

**Issue by Hendrik147** [moderndive/ModernDive_book#284]
Does the following message displays also to you after launching the bookdown rendering command in R (i.e. bookdown::render_book('index.Rmd', 'bookdown::gitbook')?

'batch' is not recognized as an internal or external command,
operable program or batch file.
/Rtools/bin/rm: cannot remove 'purl.Rout': No such file or directory

It does not look an issue, but only maybe ...

**Comment by ismayc** [comment]
Hi @Hendrik147. I'd suspect your error is a non-Mac specific error in regards to [this line](https://github.com/moderndive/ModernDive_book/blob/b1d67fe97185912d73aed3460ebeeef9d434ae90/index.Rmd#L117) and the one following that call the `system()` function. We both have Mac computers and little experience on Windows. I'd guess many of these `system()` calls can be commented out so a global search throughout the directory (and subdirectories) of files for `system()` is probably the best way to prevent this error. There might be ways to convert these commands to better work with your operating system as well, but hopefully this gives you a place to start.

**Comment by ismayc** [comment]
Here's a suggestion that might be helpful too as you transition over: https://www.statmethods.net/interface/batch.html

**Comment by Hendrik147** [comment]
Thank you so much @ismayc for looking into the issue and for suggesting a solution. I confirm that I have started using Windows 10 recently. Right now I am doing the upgrade to your latest version of moderndive.

**Comment by Hendrik147** [comment]
Just an update on this issue: 
I replaced the lines with the following:
 system('"C:/Program Files (x86)/R-3.6.0/bin/x64/R.exe" CMD BATCH --vanilla --slave
            "C:/Users/xxx/AppData/Local/gitkraken/pp-6.5.1/HR_Analytics_in_R_book_local_clone/HR_Analytics_in_R_book2/purl.R"')
system('rm "C:/Users/xxx/AppData/Local/gitkraken/pp-6.5.1/HR_Analytics_in_R_book_local_clone/HR_Analytics_in_R_book2/purl.Rout"')
However, when I launch the rendering command the scripts are not produced.
As a temporary fix, I launched the purl.R manually. This produced the R codes in the correct folder. It is important to have the same chapter sequence and titles in the purl.R and in the .bookdown.yml file.  I could not find a definitive solution

**Comment by ismayc** [comment]
Could you try using the `source()` R function and the `file.remove()` R function instead here? That might be easier than trying to do a `system()` function call.

**Comment by ismayc** [comment]
@rudeboybert To help Windows users build the book, I think it would be helpful to convert all `system()` commands to use R functions instead. What do you think?

**Comment by rudeboybert** [comment]
I'm all for it! Altho given stuff going on my course, I could only work on this later on.

**Comment by Hendrik147** [comment]
Thanks a lot.

**Comment by ismayc** [comment]
Hi @Hendrik147. Please try to build the book again from the master branch. Hopefully it goes through for you now. Let us know if not.

**Comment by Hendrik147** [comment]
Hi @ismayc, thank you. 
Please bear in mind that I will dedicate time again only next weekend. In general, I am not settled yet in updating my site with your same speed, as I am unclear on the steps that I should follow. After doing the updates several times I will get the hang of GitHub. I appreciate that my experience can be interesting for you. Apart from purl, Latex was not yet completely installed on my new Windows computer. When I am ready to give you feedback, I will not hesitate. Thanks again.
