### ISSUE TITLE
Error in the figure 8.26

### ISSUE THREAD

**Issue by xiaochi-liu** [moderndive/ModernDive_book#292]
Hi there. I found a small error in Chapter 8 Bootstrapping and Confidence Intervals.

Prior to figure 8.26, the text said to add a dashed vertical line at Ilyas and Yohan's observed proportion 0.42. However, in the figure 8.26, the vertical line showed the population proportion, 0.375, not 0.42:

![image](https://user-images.githubusercontent.com/48895627/74606334-bde79f00-5123-11ea-9c36-befe2a7f258f.png)

**Comment by rudeboybert** [comment]
Hey @xiaochi-liu, thanks for pointing this out. We'll fix this in the near future.

**Comment by ismayc** [comment]
This will be fixed at moderndive.netlify.com when #294 is merged in. moderndive.com will be updated on our next major release.
