### ISSUE TITLE
Potential Issues in  section 7.7.4 Data

### ISSUE THREAD

**Issue by kotamine** [moderndive/moderndive_book#3]
Hi I recently discovered your book. It's very helpful and I am thinking of using it with my students. 

I wonder if you have issues in section 7 starting at 7.7.4.  
https://ismayc.github.io/moderndiver-book/7-hypo.html#data-1

[movie_example.pdf](https://github.com/ismayc/moderndiver-book/files/836926/movie_example.pdf)

**Comment by rudeboybert** [comment]
Hi Kota, thanks for filing this issue. Could you elaborate further on what you mean by "issues"? The book does not compile at that section? thanks

**Comment by kotamine** [comment]
Hi, I attached a PDF file above. I couldn't attach R-file directly.   

When you regress  "rating" on "genre" (page 6),  p-value of the coefficient is 0.013.  When generating a histogram with bootstrapping, it should show about 1.3% of rejection region (page 9).  The bootstrap version of p-val was calculated to be 0.0156 (page 9). 
That's slightly different from regression p-val, which assumes normal distribution of error. 

On the website, you have figure 7.10 and 7.11.  It's not showing the correct rejection region, I believe.  This is in contrast to what you did for Figure 7.4.

**Comment by kotamine** [comment]
I really like sections 3-5. I never knew how to use dplyr functions.  This book can become a very good cookbook for a modern introduction to R and data exploration.  

I am an economist, so I am looking at Microeconometrics by Cameron and Trivedi. 
For example, on p359 it has;

"For asymptotic refinement to occur, the statistic being bootstrapped must be an asymptotically
pivotal statistic, meaning a statistic whose limit distribution does not depend
on unknown parameters."

"Estimators are usually not asymptotically pivotal. However, conventional asymptotically
standard normal or chi-squared distributed test statistics, including Wald,
Lagrange multiplier, and likelihood ratio tests, and related confidence intervals, are
asymptotically pivotal."

p364; 
"An asymptotic refinement is based on the t-statistic, which is asymptotically pivotal."

So, one can obtain bootstrap replications of t-statistics (i.e. (theta_bt - theta_obs)/theta_bt for each case of bootstrap replication bt)  and use its distribution to derive a confidence interval (equation 11.6 on page 364). 

I could be wrong, so you might want to consult a statistician.

**Comment by ismayc** [comment]
Hi Kota.  You found a typo where I used `movies_trimmed` where I should have used `movies_genre_sample` instead.  Using this aggregated data set that was created using `group_by` does mean that the `ungroup()` function is necessary to do `shuffle`ing later for the permutation test.  I have updated the book to account for this in this [commit](https://github.com/ismayc/moderndiver-book/commit/24c13f78433a7e208598387b53a737cdd43ca9f5).

I think that adding a parametric bootstrap down the road to the book does make sense so I have added the enhancement tag here.

**Comment by rudeboybert** [comment]
Hi @kotamine, sorry for the extreme delay in replying, but we finally got around to revamping our approach to statistical inference, in particular using the new [`infer`](http://infer.netlify.com/) package for tidyverse-friendly statistical inference, so unfortunately your original questions and comments are now moot. If you'd like to preview our still "under construction" approach, take a look at the development version of Modern, in particular:
- [Chapter 8: Sampling](https://moderndive.netlify.com/8-sampling.html)
- [Chapter 9: Confidence intervals](https://moderndive.netlify.com/9-confidence-intervals.html), both CLT and resampling based
- [Chapter 10: Hypothesis testing](https://moderndive.netlify.com/10-hypothesis-testing.html), both CLT and resampling based

If you have any questions or comments, please don't hesitate to file another issue!
