### ISSUE TITLE
Learning Check 6.1 (Issue with Regression Model Name)

### ISSUE THREAD

**Issue by CJParkNW** [moderndive/ModernDive_book#301]
Minor error with Learning Check 6.1 in Chapter 6 and under its solution. It asks us to compute the regression points for the parallel slopes model, but it lists score_model_interaction as the name we saved it under. I believe it's supposed to be score_model_parallel_slopes.

**Comment by rudeboybert** [comment]
Thanks @CJParkNW, this was fixed in pull request #302
