### ISSUE TITLE
YAML title in index.Rmd

### ISSUE THREAD

**Issue by Hendrik147** [moderndive/ModernDive_book#305]
I am pleased to say that I found an issue, but also the solution: In the first lines of the index.Rmd file it should say:

---
title: "`r ifelse(knitr::is_latex_output(), 'Statistical Inference via Data Science:  A ModernDive into R and the Tidyverse', 'Statistical Inference via Data Science')`"
author: "`r ifelse(knitr::is_latex_output(), 'Chester Ismay and Albert Y. Kim', 'Chester Ismay and Albert Y. Kim <br> Foreword by Kelly S. McConville')`"

and the inverted commas " should not be used as it triggers an unclear error message in my Windows PC when launching the render book command: 
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Parser error: while parsing a block mapping at line 1, column 1 did not find expected key at line 1, column 46

**Comment by ismayc** [comment]
Hi @Hendrik147. What is the proposed solution here? I'm only seeing what currently exists for the  code on [this line](https://github.com/moderndive/ModernDive_book/blob/d7ec4d19fce61a54ad63ffb04a6fde522d399df6/index.Rmd#L2) of the `index.Rmd` file.

**Comment by Hendrik147** [comment]
Hi @ismayc,
the proposal is to replace the " with ' only. Just by doing this replacement, the error was not appearing anymore.

**Comment by ismayc** [comment]
If we replace each of the `"` with a `'`, we get an error since we already use `'` around some of the text fields. Are you not getting this same error using `'` throughout?

**Comment by ismayc** [comment]
Ah, I see what you are asking now. Replace all `'` with `"` and vice versa on those lines. I'm trying it out now to see if there is any impact on a Mac when building.
