### ISSUE TITLE
After release, lock master branch; do all editing in dev branch

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/moderndive_book#31]

**Comment by ismayc** [comment]
Also copy over all old versions of the textbook, using `file.copy()` via a bash file to `docs`.

**Comment by rudeboybert** [comment]
Switch of plans. Master branch is development version, and instead have `release` branch for latest release.

**Comment by rudeboybert** [comment]
Add reference to this in #32 for old versions issue
