### ISSUE TITLE
environment learncheck not defined

### ISSUE THREAD

**Issue by Hendrik147** [moderndive/ModernDive_book#310]
A Latex error appears at the end of the book rendering saying that the environment learncheck is undefined. It seems to be missing in the krantz.cls file, but I am not sure how to define it.

https://tex.stackexchange.com/questions/462814/defining-a-new-environment

**Comment by rudeboybert** [comment]
Hi Hendrik, alas the krantz.cls file is provided by CRC press so we only have a limited understanding of it. Could you post the LaTeX error? We'll see if we can come up with a quick fix.

**Comment by rudeboybert** [comment]
Oh wait, I completely forgot. This environment is one we defined here; https://github.com/moderndive/ModernDive_book/blob/master/latex/preamble.tex. You need to ensure that it is included in your LaTeX compiling.

**Comment by Hendrik147** [comment]
Thanks, @rudeboybert, 

when downloading the ModernDive repository (with no amendments whatsoever) I expect it to run locally to generate pdf and all the html files in one go, but currently, I do not achieve this.

When I launch the render book command manually:

bookdown::render_book("index.Rmd", "bookdown::pdf_book",
                      clean = FALSE,
                      clean_envir = FALSE,
                      encoding = 'UTF-8')

I get the following messages at the end:

output file: ModernDive.knit.md
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS ModernDive.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output ModernDive.tex --self-contained --table-of-contents --toc-depth 2 --number-sections --highlight-style tango --pdf-engine pdflatex --variable graphics --lua-filter "C:/Users/hfedd/Documents/HR_Analytics_in_R_book3/packrat/lib/x86_64-w64-mingw32/3.6.0/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/Users/hfedd/Documents/HR_Analytics_in_R_book3/packrat/lib/x86_64-w64-mingw32/3.6.0/rmarkdown/rmd/lua/latex-div.lua" --wrap preserve --variable tables=yes --standalone -Mhas-frontmatter=false --filter "C:/Program Files/RStudio/bin/pandoc/pandoc-citeproc.exe" 
! LaTeX Error: Environment learncheck undefined.

Error: LaTeX failed to compile ModernDive.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See ModernDive.log for more info.
In addition: There were 23 warnings (use warnings() to see them)

The warnings I ignore, for now, as it is all minor stuff. My priorities are the pdf and the html files for now. 
The preamble.tex is included under the latex folder, so I believe it is included in the Latex compiling.
The relationship error message above and krantz.cls file is proven by introducing small modifications in the krantz.cls and resulting in different error messages.

**Comment by Hendrik147** [comment]
Maybe a clue: I noticed that in YAML of index.Rmd it says that at line 19
documentclass: krantz

Maybe another useful clue at the last paragraph of:
https://bookdown.org/yihui/bookdown/yaml-options.html

**Comment by ismayc** [comment]
As Bert mentioned, the learncheck environment is defined in `preamble.tex` [here](https://github.com/moderndive/ModernDive_book/blob/08e9e5909d7261f20873fa87551c47138283281c/latex/preamble.tex#L100). `krantz` is book template used by CRC Press in LaTeX. I'm going to close this issue since I'm not sure if we are able to assist. If you are looking for a PDF version of the book, maybe it's best to use the default `pdf_book` template instead of what we are using?
