### ISSUE TITLE
Rendering of inline math styling in browsers

### ISSUE THREAD

**Issue by AlarithUhde** [moderndive/ModernDive_book#313]
First of all, thanks for the great book! I'm trying to report problems while working through it.

Starting with chapter 5, I have encountered some problems with the math rendering, especially in firefox. I guess that might not be a problem specific to this book but in bookdown or some other tool. The inline math notation in firefox 68.5.0esr on my computer looks like this:

![Bildschirmfoto zu 2020-03-10 12-45-39](https://user-images.githubusercontent.com/6137672/76309524-3c6fd080-62cd-11ea-9663-7e9a285ad1d9.png)

It looks fine in Chromium 79.0.3945.130:

![Bildschirmfoto zu 2020-03-10 12-46-00](https://user-images.githubusercontent.com/6137672/76309581-590c0880-62cd-11ea-9808-35aaedcb2c56.png)

However, in line:

https://github.com/moderndive/ModernDive_book/blob/master/05-regression.Rmd#L430

there is a slight issue with the index rendering of escape characters even in Chromium:

![Bildschirmfoto zu 2020-03-10 12-46-15](https://user-images.githubusercontent.com/6137672/76309644-76d96d80-62cd-11ea-8129-9c78c64372b0.png)

As I said, I think the general rendering problem is probably in some other package, but the last one may be specific to this book.

**Comment by ismayc** [comment]
Hi @AlarithUhde. You're very welcome! Thanks much for reporting your issues.

Unfortunately, I'm not able to reproduce your Firefox rendering errors. I'm using Firefox 74.0 on a Mac and after a few seconds the rendering goes through just fine.

The other issue you report in terms of the \ [here](https://github.com/moderndive/ModernDive_book/blob/master/05-regression.Rmd#L430) does appear to be a bug. It looks like the `\` is needed for the PDF build but needs to be removed for the HTML build. I'm going to try to experiment further with this.
