### ISSUE TITLE
Unclear formulation

### ISSUE THREAD

**Issue by AlarithUhde** [moderndive/ModernDive_book#315]
The first sentence on line:

https://github.com/moderndive/ModernDive_book/blob/master/06-multiple-regression.Rmd#L1152

doesn't make sense.

**Comment by ismayc** [comment]
Can you please provide a suggestion on how the wording should change?

**Comment by AlarithUhde** [comment]
Yes, sure. First of all, I'm not an English native, so I'm not sure if the grammar of this sentence is correct as is. To me, the formulation "among [...] the examples [...] involves polls" sounds wrong. I would suggest e.g.:

- For example, the most well-known methods of sampling involve *polls*.
- For example, among the most well-known processes of sampling are *polls*.
