### ISSUE TITLE
Small changes before Saturday

### ISSUE THREAD

**Issue by ismayc** [moderndive/moderndive_book#32]
This will serve as future release checklist as well.

- [x] Just this time: get package list consistent
- [x] Check for broken `@` and `??` references
- [x] Ensure Chapter/Section/Subsection consistency. Ex: 3/3.1/3.1.2
- [x] Hide all Learning Check solutions
- [x] Take banner off of `master` branch `docs` deploy after we create a `dev` branch.
- [x] Make changes in `index.Rmd` to update versions of development and released.
- [x] Tag release on GitHub for new released version.
- [x] Update past versions list in [Section 1.4](http://moderndive.com/index.html#about-book). See #23 and #31  
- [x] Change travis to look for changes on the `dev` branch and then publish to `gh-pages` (for Albert's class on Monday).
- [x] Create a referral page from https://github.com/ismayc/moderndiver-book to https://github.com/moderndive/moderndive_book (Contents in the old repo should be removed prior to the next major release--likely this summer.)
- [x] Change links to script files to be to https://moderndive.com/scripts/ for the released version of the book. Not that big of a deal but it would be confusing if we changed some of the code in the development version of the book and then someone was trying to run the ModernDive.com code instead. We should probably set a toggle for this. (Delayed until next release.)

**Comment by rudeboybert** [comment]
Hey @ismayc I'm done all my TODO's on this list from back in January and copied over all elements to the "release checklist" in the Google Doc, so I removed myself from assignees.

**Comment by ismayc** [comment]
@rudeboybert I finally copied over your slick trick to get https://ismayc.github.io/moderndiver-book/ to route to https://www.moderndive.com. Nice work!

**Comment by rudeboybert** [comment]
It's a hack, but it gets the job done. #DoneIsBetterThanPerfect
