### ISSUE TITLE
Typo in Chapter 9

### ISSUE THREAD

**Issue by AlarithUhde** [moderndive/ModernDive_book#320]
On line:

https://github.com/moderndive/ModernDive_book/blob/master/09-hypothesis-testing.Rmd#L1299

"degrees Kelvin" -> "Kelvin"

**Comment by rudeboybert** [comment]
Hey @AlarithUhde, thanks for pointing out all these typos! They are very helpful.

One question for you. Would you be up for fixing typos yourself via GitHub pull requests? If you are not familiar with GitHub PR's, long story short you would propose the edits directly to the source code, which we would then verify and then approve. Benefits of this model:
1. Benefits to us: the typo can be located and corrected much quicker
1. Benefits to you: you would get acknowledged on our [contributors page](https://github.com/moderndive/ModernDive_book/graphs/contributors)

While there are more complicated ways to do this, the simplest way would be using the GitHub GUI as seen in this [screencast](https://www.loom.com/share/29d994e9beff4de7b6a3ca8b14b6464a).

This being said, please submit pull requests if you see a benefit to learning GitHub pull requests or to being acknowledged on our contributors page. We would still appreciate the current model of typo reporting. They are of huge help to us!

**Comment by AlarithUhde** [comment]
Thanks a lot for the info and especially the screencast! I will try this approach next time. However, I haven't found any other typos in the remaining chapters until Chapter 11 (I haven't read the Appendix entirely).

**Comment by rudeboybert** [comment]
Again, please only take the pull request approach if there is value in it for you. Reporting typos as you've been doing so far is still very much appreciated!

No typos? What? 😉
