### ISSUE TITLE
patchwork on CRAN

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [moderndive/ModernDive_book#321]
The footnote at https://moderndive.com/E-appendixE.html says the patchwork package isn't on CRAN, but it's now there (https://cran.r-project.org/web/packages/patchwork/index.html) so the footnote should be removed.

**Comment by ismayc** [comment]
It will be removed on the next release of the book. The current developmental version of the book with it removed is at https://moderndive.netlify.com/e-appendixe.
