### ISSUE TITLE
Give a summary of the `get_` functions

### ISSUE THREAD

**Issue by ismayc** [moderndive/moderndive_book#33]
I think students may struggle a bit to understand when to use each of the three `get_` functions since they are similar. Would be useful to add a closing summary to Chapter 7 discussing this. (Not pressing, but helpful to include on the next big release.)

**Comment by rudeboybert** [comment]
Yeah, we'll see when I battle test it start on [Feb 19th](https://rudeboybert.github.io/STAT135/index.html#schedule). Note I don't use the third one `get_regression_summaries` at all.

**Comment by rudeboybert** [comment]
![flowchart 011-cropped](https://user-images.githubusercontent.com/4574203/42728611-36573ecc-878c-11e8-870c-785fd580848a.png)
