### ISSUE TITLE
Alternative Hypothesis

### ISSUE THREAD

**Issue by mt-edwards** [moderndive/ModernDive_book#332]
There is the use of H_a rather than H_A to denote an alternative hypothesis on lines 539 and 1122.

https://github.com/moderndive/ModernDive_book/blob/c37f750db367fa07218f35cdd1d9db5047cfd551/09-hypothesis-testing.Rmd#L539

**Comment by ismayc** [comment]
Thanks! Have fixed this and included it in the #331 PR to be merged soon.
