### ISSUE TITLE
p-Value Discription

### ISSUE THREAD

**Issue by mt-edwards** [moderndive/ModernDive_book#333]
I think the words "above" and "below" need to be reverse for the correct p-value description.

https://github.com/moderndive/ModernDive_book/blob/c37f750db367fa07218f35cdd1d9db5047cfd551/09-hypothesis-testing.Rmd#L1481

**Comment by ismayc** [comment]
Nice catch! This was changed when we switched the order of "Action" and "Romance" but we forgot to tweak the wording. Appreciate you letting us know! Will be fixed in #331
