### ISSUE TITLE
Refactor Netlify deployments

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/ModernDive_book#340]
Refactor gh pages & netlify deployments so that there are only two:

1. As before, `release` branch deploys to moderndive.com
1. A new `v2` branch deploys to moderndive.netlify.app. This will correspond to preview of 2nd Ed and will include non-cosmetic changes like #271 #296 #304 and beefed-up CLT section of Ch7 Sampling.

Under this new scheme, `master` branch doesn't deploy anywhere.

Also update `README.md` informing user of new deployments

**Comment by ismayc** [comment]
Maybe also tweak the `install.packages()`code in index.Rmd to ask before installing too? Check how this is done with the `remotes::install_github()` function code?

**Comment by rudeboybert** [comment]
Ok. will make this it's own issue.

**Comment by rudeboybert** [comment]
@ismayc CLOSE IT!!!!
