### ISSUE TITLE
Data Camp class on Effective Data Storytelling not working

### ISSUE THREAD

**Issue by davidkane9** [moderndive/moderndive_book#38]
The book recommends a Data Camp class and provides this link

https://campus.datacamp.com/courses/effective-data-storytelling-using-the-tidyverse/

Although other Data Camp courses work fine for me, this one does not. I always get this message:

> Setting up your session took too long.
> If the problem persists, please report an issue.

Should this be working for me? I would like to assign it to the students in my Harvard class next week.

**Comment by ismayc** [comment]
@davidkane9 Thanks for reporting this. The link recently changed for the course to https://campus.datacamp.com/courses/effective-data-storytelling-using-the-tidyverse-free/. I will update the link on moderndive.netlify.com soon.

**Comment by ismayc** [comment]
https://moderndive.netlify.com has been updated. Please let us know if you have any other troubles with this. Thanks again!
