### ISSUE TITLE
Introduction of cut( ) function in C.1.5 Converting a numerical variable to categorical one

### ISSUE THREAD

**Issue by xiaochi-liu** [moderndive/ModernDive_book#382]
In the current C.1.5 "Converting a numerical variable to categorical one", when introducing other options with the `cut` function, it is said:

"You could also have RStudio equally divide the variable into a balanced number of groups. For example, specifying `breaks = 3` would create 4 groups with approximately the same number of values in each group."

I think setting `breaks = 3` in the `cut` function would give you 3 equal intervals, and the number of values in each interval may be varied.

**Comment by rudeboybert** [comment]
Thanks @xiaochi-liu!
