### ISSUE TITLE
DataCamp access to "Effective Data Storytelling using the Tidyverse"

### ISSUE THREAD

**Issue by davidkane9** [moderndive/moderndive_book#39]
I have assigned my students to take the Data Camp class:

https://campus.datacamp.com/courses/effective-data-storytelling-using-the-tidyverse-free

After finishing Applying R Basics, they are confronted with an Upgrade Your Account to Continue screen. 

<img width="1198" alt="screen shot 2018-03-01 at 12 01 29 am" src="https://user-images.githubusercontent.com/4552851/36846559-289443a2-1d29-11e8-969c-5db6307bf86d.png">

With no obvious way to continue without paying.

I tested it myself and the same thing happened. I assume that the whole course should be free . . .

**Comment by ismayc** [comment]
Hmm, this appears to be a bug. I will report it to the relevant team at DataCamp. In the meantime, I recommend you sign up for a Data Science for Academics group at https://www.datacamp.com/groups/education. This will grant yourself and all your students premium access to all of our content for 6 months.

**Comment by ismayc** [comment]
@davidkane9 Can you share your email address so we can look into why this is happening on you and your students accounts as we aren’t able to replicate with other accounts?

**Comment by davidkane9** [comment]
dave.kane at gmail

**Comment by davidkane9** [comment]
FYI: One student has completed the lesson successfully and gotten the badge.

**Comment by ismayc** [comment]
Thanks. DataCamp's engineering team is still digging into the original issue. I hope that the academic group option works well for you.

**Comment by Teili** [comment]
Now, I am having exactly the same problem as David year ago. Started Introduction to R course and after finishing Chapter 1 it gives me screen "Upgrade your account to continue" without giving me any opportunity to continue without paying. What should I do?

**Comment by ismayc** [comment]
Can you please email me at chester.ismay@gmail.com? “Introduction to R” is now a Premium course at DataCamp.

**Comment by Teili** [comment]
Oh, I didn't realize the whole course is not free anymore. Thanks.

**Comment by Tripartio** [comment]
@ismayc, does this mean that DataCamp no longer offers any completely free courses at all now? Do you have any idea why the Intro to R course is no longer free?

**Comment by ismayc** [comment]
@Tripartio Please reach out to support@datacamp.com with your question and they'd be happy to follow-up with you.

**Comment by Tripartio** [comment]
Thanks, @ismayc; I contacted support and they affirmed that they no longer offer completely free courses; it's only the first chapter now. :-(
