### ISSUE TITLE
Replace `sample_n()` with `slice_sample()`

### ISSUE THREAD

**Issue by ismayc** [moderndive/ModernDive_book#396]
https://dplyr.tidyverse.org/reference/sample_n.html

**Comment by rudeboybert** [comment]
Note from @ismayc: Simon has implemented a `rep_slice_sample()` function in {infer} that should be merged in soon: https://github.com/tidymodels/infer/pull/362/files. Might be best to add a reminder to convert all the `rep_sample_n()` over when the next version of {infer} goes to CRAN.

**Comment by ismayc** [comment]
@avaldivi6 Just remembered this. `sample_n()` has been superseded by `slice_sample()`, so we should switch it and also `rep_sample_n()` over to `rep_slice_sample()`.
