### ISSUE TITLE
Link to the section 9.1.4 in the menu points to the chapter 7

### ISSUE THREAD

**Issue by hamonk** [moderndive/ModernDive_book#402]
When I go over the link to the section "9.1.4 What did we just do?", I see it redirects to https://moderndive.com/7-sampling.html#what-did-we-just-do

Maybe it is because the 2 sections share the same name "What did we just do?"

<img width="389" alt="wrong link" src="https://user-images.githubusercontent.com/840608/93397650-05fcaa80-f848-11ea-9697-552b7b357621.png">

**Comment by rudeboybert** [comment]
Ah, thanks for this @hamonk. We'll fix this shortly

**Comment by rudeboybert** [comment]
Thanks @hamonk!
