### ISSUE TITLE
Missing values in Chapters 5 & 6

### ISSUE THREAD

**Issue by daniloderosa** [moderndive/ModernDive_book#429]
![Schermata 2021-08-20 alle 19 33 42](https://user-images.githubusercontent.com/74054364/130272043-19e9a127-c24c-4dcd-9c29-8d68ed57c8c4.png)
![Schermata 2021-08-20 alle 19 38 41](https://user-images.githubusercontent.com/74054364/130272543-40e871f2-5499-402e-8fbf-673968bd4cd3.png)

In Chapters 5 & 6, when you run the regression there's a problem with the intercept of categorical variables: every time (in almost every single table and formula) it's missing, as you can see in the picture. I can't actually point to one single chunk because there's a problem in almost every single of them (but, as I said, I think the problem lies when there's a categorical variable in the model).

**Comment by rudeboybert** [comment]
Hey @daniloderosa thanks for bringing this to our attention, I'll fix this ASAP

**Comment by rudeboybert** [comment]
Thanks @daniloderosa (and Aaron C who emailed me separately). The issue was the `moderndive` package now spits out different labels for offset categorical variable levels; they now include a `": "` between the variable name and the level. It's been fixed online
