### ISSUE TITLE
"10.9.8 Simulated data" needs some clarification

### ISSUE THREAD

**Issue by rasmus1610** [moderndive/moderndive_book#43]
First of all thank you so much for your book. It made sampling and hypothesis testing so much more clear for me. Something I never really understood in med school. 

One thing I tripped over a little bit is the section "10.9.8 Simulated data" in the chapter on hypothesis testing the difference of means.  Especially the "tactile experiment" wasn't clear the first time I read it. I needed like 5-6 reads to fully understand the idea behind the experiment: 

> The next step is to put the two stacks of index cards together, creating a new set of 68 cards. If we assume that the two population means are equal, we are saying that there is no association between ratings and genre (romance vs action). We can use the index cards to create two new stacks for romance and action movies. First, we must shuffle all the cards thoroughly. After doing so, in this case with equal values of sample sizes, we split the deck in half.

The thing that wasn't clear for me was, that you build two new stacks for "action" and "romance" movies that do not consist entirely of one genre but is a mixture of both. Since the H0 hypothesis is that there is no difference between the ratings of the two genres that's a valid way to simulate the H0 hypothesis. But that wasn't that clear for me. Maybe a small sketch of the experiment or something would make this much more clear. Even a sentence like _"Note that the new stack for action and romance movies does not consist entirely of the specific genre"_ or something along those lines would be awesome.

I hope my point is clear. I would love to assist clarifying this section

Thanks again for your awesome content 👍

**Comment by ismayc** [comment]
Thanks much for the feedback, @rasmus1610! I think some visuals would go a long way here as well. We will be working on revamping the later chapters of the book to discuss the `infer` package and I'll work on including some more details here as well. Would you be OK if I tagged you when that is done to get your feedback again?

**Comment by rasmus1610** [comment]
Tagging me would be awesome :)
Thank you for your fast response.

**Comment by ismayc** [comment]
@rasmus1610 I haven’t had a chance to create diagrams or take pictures of the experiment. Do you know of any nice tools for sketching something like this?

**Comment by rasmus1610** [comment]
Sorry for the late answer. 

Unfortunatly I don't know any specific tools. I would try some vector tool like figma.com, Sketch or Adobe Illustrator...

**Comment by ismayc** [comment]
@rasmus1610 We still haven't included diagrams as I need to get up-to-speed on how this might be done, but we have updated ModernDive.com recently to version 0.4.0 to use the {infer} R package, which should help explain some of the inference details a bit. We'd love your feedback on this.

**Comment by rasmus1610** [comment]
Sorry for replying so late. 
I think it is much clearer now. But I would still write that the new so called "action movie stack" is not consisting of action movies but of a mixture of both genres just to make it super clear.

**Comment by ismayc** [comment]
I've added in some clarifying text. Thanks much, @rasmus1610!

 > Note that the **new** "romance movie stack" will likely have some of the original action movies in it and likewise for the "action movie stack." Since we are assuming that each card is equally likely to have appeared in either one of the stacks this makes sense.

**Comment by ismayc** [comment]
https://moderndive.netlify.com/10-hypothesis-testing.html#simulated-data
