### ISSUE TITLE
Scrap soft introduction to dplyr and pipe in Chapter 2 Data Viz

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/ModernDive_book#435]
Oi @ismayc how would you feel about scrapping the dplyr code that creates `alaska_flights` & `early_january_weather` and instead have these datasets be included in `moderndive`? Our soft introduction to dplyr functions and the pipe in Chap 2 on data viz (before Chap 3 on data wrangling) is consistently tripping up a lot of the newbies

**Comment by ismayc** [comment]
Definitely OK with me!

**Comment by wmorgan485** [comment]
I agree. When the pipe was introduced in Chapter 2, students didn't have enough context yet to understand its function and importance.
