### ISSUE TITLE
Deploy to netlify using GitHub Actions

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/ModernDive_book#436]

**Comment by rudeboybert** [comment]
Heads up @ismayc I deleted `_travis.yml` per this [tweet](https://twitter.com/peter_szilagyi/status/1437646118700175360)

**Comment by ismayc** [comment]
Yikes! Good call

**Comment by rudeboybert** [comment]
Learn `_bookdown.yml` automation with Netlify

**Comment by ismayc** [comment]
https://github.com/r-lib/actions/tree/master/examples#build-bookdown-site

**Comment by rudeboybert** [comment]
Closed with all commits on the day of 478d844104f87bd2730c85df75a257d025427b47
