### ISSUE TITLE
v2 and master branch issue

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/ModernDive_book#440]
No longer have
* master -> moderndive.com
* v2 -> moderndive.netlify.app (which we need to keep for legacy reasons)

rather
* have master and v2 have same content, and moderndive.com and moderndive.netlify.app read from the same branch
* process: make changes in v2 then merge into master to keep track of changes

**Comment by rudeboybert** [comment]
Hey @ismayc what was the reason for the new proposed process: "make changes in v2 then merge into master to keep track of changes"?

Why not just make all changes in master and get rid of v2 branch altogether?

We would still need to ensure that moderndive.com and moderndive.netlify.app read from the same branch b/c there may be people out there who are still using the latter.

**Comment by ismayc** [comment]
I think commit history on master should be fine. I just like being able to review changes and a PR does that in batch nicely.

**Comment by ismayc** [comment]
Informally is fine. I don't need to review small changes/typos and I want you to be able to fix things without waiting for me if needed.
