### ISSUE TITLE
Getting error in building to epub format

### ISSUE THREAD

**Issue by rohitvishwakarma1819** [moderndive/ModernDive_book#459]
I'm trying to build this book to epub format but getting error which says -

<img width="630" alt="Screenshot 2022-07-15 at 10 37 54 AM" src="https://user-images.githubusercontent.com/46737549/179155012-b1d4e035-1c14-4fa0-a6aa-3573f9fdf199.png">

# Steps Followed 

I added below line to *_output.yml* file at the last

``yml
bookdown::epub_book: default
``

Any help would be appreciated.

**Comment by ismayc** [comment]
Fixed in #460
