### ISSUE TITLE
Rendering error-section reference in Ch. 9

### ISSUE THREAD

**Issue by elleobrien** [moderndive/ModernDive_book#462]
In Chapter 9.3 (Conducting Hypothesis Tests, 2nd sentence), one of the hyperlinked references is rendering as `Subsection [??](https://moderndive.com/9-hypothesis-testing.html#shovel-1000-times)`. 

This is being viewed with Vivaldi browser.

**Comment by rudeboybert** [comment]
Hi @elleobrien thanks for filing this! Turns out we had two whole missing subsections in Chap 7 😮! All this because we forgot to close an HTML comment with `-->`. We're on it now.
