### ISSUE TITLE
Ensure we can get semi-frequent estimates of delta in PDF page count

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/ModernDive_book#482]

**Comment by ismayc** [comment]
@rudeboybert @avaldivi6  V1 of the book had 498 pages in the PDF (12 size font).

The current number of pages in the PDF (including updates to Chapter 7, but no updates to Chapter 8) is 480 pages. This is using 11 size font.

I'll post updates here either every 2 weeks or whenever Arturo has made significant progress on a chapter.

**Comment by ismayc** [comment]
@rudeboybert @avaldivi6 I've tried to sync a fork up with Arturo's repo that will build a PDF of Arturo's repo using GitHub Actions. It's supposed to check "every few hours" for updates. On the main page at https://ismaytemp.github.io/ModernDive_book/ if you scroll down a bit, you can see how many pages are in the PDF currently (478) at the moment.
