### ISSUE TITLE
Appendix C - Interactive Plot 

### ISSUE THREAD

**Issue by gungorMetehan** [moderndive/ModernDive_book#488]
Does the interactive plot code work properly (HTML)?

![App_C](https://github.com/moderndive/ModernDive_book/assets/102655648/d58e7851-76de-4385-b05f-5bd13593783a)

**Comment by ismayc** [comment]
Hmm, it does appear to be broken. We'll need to look into this.

**Comment by ismayc** [comment]
This doesn't seem to work in the Viewer in RStudio either currently.

**Comment by ismayc** [comment]
Looks like it just needed a conversion to a data frame. I'll get this updated now:

```r
library(dygraphs)
library(nycflights13)
flights_day <- mutate(flights, date = as.Date(time_hour))
flights_summarized <- flights_day %>%
  group_by(date) %>%
  summarize(median_arr_delay = median(arr_delay, na.rm = TRUE)) %>%
  as.data.frame()
rownames(flights_summarized) <- flights_summarized$date
flights_summarized <- select(flights_summarized, -date)
dyRangeSelector(dygraph(flights_summarized))
```
