### ISSUE TITLE
Add docs/ to .gitignore

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/moderndive_book#50]
@ismayc Is there any reason to keep `docs/` synced on GitHub, since travis-ci renders the book to the `gh-pages` branch? I feel like we should only sync changes to `.Rmd` and `.yml` files and images/data files, otherwise it increases the chances of merge conflicts and makes for harder commit/branch comparisons.

**Comment by rudeboybert** [comment]
Also perhaps instead have travis-ci copy the contents of the `gh-pages` rendered book to the `master` branch `docs/` folder in the case there are still floating GitHub pages <https://moderndive.github.io/moderndive_book/> links out there?

**Comment by ismayc** [comment]
I like being able to have a backup just in case travis isn’t working. Merge conflicts should be pretty minimal and if they do exist we can just pull down and then recompile. The `docs` folder doesn’t have to be updated that frequently but can still be useful at times I think.

**Comment by rudeboybert** [comment]
fine by me
