### ISSUE TITLE
Release steps

### ISSUE THREAD

**Issue by ismayc** [moderndive/ModernDive_book#57]
Copied from corresponding Google Doc (only the first part):

# 1. Final edits to `.Rmd` files

## a) Formatting
- [ ] Borders of all histograms should be white, making the binning structure easier to read.
- [ ] Use `computer font` for all computing concepts: `function()`, `data_frame`, `variable_names`, `package_name`.
- [ ] Remove all `&`, `%`, and `_` in `fig.cap` for R chunk options since they break PDF build
- [ ] Ensure no code exceeds 80 characters. While HTML code block outputs tolerate >80, PDF code block outputs do not.
- [ ] Ensure `skimr::skim()` code is not actually run, but all calls and outputs are hard-coded (with `hist` preview removed and `---` output cut down to 80 characters), since this will break all `knitr::kable()` code for rest of book.
- [ ] Apply {styler} code to all internal code (i.e. code the reader doesn't see) using `styler`'s RStudio Add-In.

## b) References
- [ ] Search for all broken references (search for @ref and ?? in html output)
- [ ] Maintain Chapter/Section/Subsection naming consistency
- [ ] Ensure all Figures & Tables are referenced.
- [ ] If possible, ensure index is up-to-date by adding `\index{<term>}` tags

## c) Dataset management
- [ ] Remove all `load()` calls
- [ ] Ensure all CSV’s are loaded from moderndive.com and not other sites. See `index.Rmd`, `set-options` R chunk, copy all needed csv files to `docs/`
- [ ] Create bit.ly links for all linked Google Docs

## d) Spell check
- [ ] Do it in RStudio.
- [ ] Scan over all changed content to make sure grammar is correct.

## e) R Scripts: Make sure docs/scripts folder contains the appropriate scripts
- [ ] Development version should link to moderndive.netlify.app/scripts since code may be updated in development causing problems if someone on moderndive.com is trying to look over all the code for what is there
- [ ] If possible, go over all code blocks and ensure that `purl = FALSE` is set for all code chunks we don't want shared.

## f) ETC
- [ ] Ensure only Shutterstock licensed photos/images are used.
- [ ] If possible, delete contents of `rds/` and rebuild all `.rds` files in case any got stale. 

# 2. Final sanity checks

- [x] Update all R packages before one final build
- [x] Build PDF version
- [x] Ensure that `.travis.yml` does not have any GitHub development `.9000` versions of packages.

# 3. Switch from dev to release version on GitHub:

## a) Create new GitHub branch
- [x] Create `update-release` branch to be used for pull request.

### At the top
- [x] YAML: Change `r format(Sys.time(), '%B %d, %Y')` to release date of form “January 1, 1970”

### set-options R chunk
- Current version information:
  - [x] Remove .9000 and bump version number
  - [x] Set date to release date: replace `format(Sys.time(), '%B %d, %Y')` with date of form “January 1, 1970”
- Latest release information:
  - [x] Update to release values
- CRAN packages needed:
  - [x] Ensure only CRAN versions used
  - [x] Periodically: Do a search for use of all packages and remove those no longer used

### Lower in the file
- [x] Comment out development version warning block
- [x] Flip `dev_version` boolean to `FALSE`

### Section 1.4 “About this book”
- [x] Latest published version: ensure info is correct
- [x] Previous versions: Add previous version info
- Add previous version to `previous_version/` folder. Steps:
  - [x] Go to `previous_versions/` and add new subfolder for soon-to-be previous version
  - [x] Go to GitHub releases pages and download .zip of source code of soon-to-be previous version
  - In `index.Rmd`
    - [x] Uncomment notice about this being an out-of-date version and hard-code version number
    - [x] Ensure comment is surrounded by `***` to highlight this note
  - [x] Build book and delete redundant nested `docs/previous_versions`
  - [x] Copy contents of `docs/` folder to the new subfolder in `previous_versions/`

## d) Edit other files
- [x] NEWS.md: Update with all significant changes from this TODO
- [x] `.gitignore`: Remove `bib/packages.bib` and `docs/`

## e) Final step

- [x] Clean and rebuild book

# 4. Publish release

- [ ] Merge `dev-to-release-vX.X.X` branch into `master`
- [ ] Merge `master` into `release` via PR (trick to remember: right into left). Or consider doing [this](https://github.com/githubteacher/github-for-developers-sept-2015/issues/648)?
- [ ] Rebuild `release/docs` and commit. You might need to remove `docs/` from `.gitignore` to be able to commit to release branch
- [ ] Tag release on GitHub
- [ ] Add link to **Previous versions** around line 474 of index.Rmd of most recent previous version.
- [ ] Send email to MailChimp
- [ ] Make sure all links in left-hand navbar index work
- [ ] Relatedly, ensure `moderndive` package on CRAN is updated around same time as ModernDive book version bump.

# 4. Revert back to dev version on GitHub:

## a) Create new GitHub branch
- [ ] Create `release-to-dev` branch to be used for pull request. See [example commit](https://github.com/moderndive/moderndive_book/pull/56/files) on GitHub to revert back to devel version by undoing all changes to:

### At the top
- [ ] YAML: Change release date back to `r format(Sys.time(), '%B %d, %Y')`
- [ ] Return “development branch” version warning block and flip `dev_version` flag

### set-options R chunk
- Current version information:
  - [ ] Add .9000 to version number
  - [ ] Set date to `r format(Sys.time(), '%B %d, %Y')`
  
## c) Edit other files:
- [ ] NEWS.md: Add section for new dev version
- [ ] Add `bib/packages.bib` to `.gitignore`
- [ ] Revert `.travis.yml` so that `infer` and `moderndive` packages are github dev versions

**Comment by ismayc** [comment]
@rudeboybert Here is a breakdown of how things deploy now:

- https://moderndive.netlify.com is generated by the `_travis.yml` file on the `master` branch. It automatically updates the `gh-pages` branch (which is then deployed using Netlify) with a bookdown build when changes are made to files on the `master` branch.
- https://moderndive.github.io/moderndive_book comes from the `docs` folder on the `master` branch. This is useful if for some unlikely reason netlify.com is down and we'd like to check a build.
- https://moderndive.com, https://www.moderndive.com, https://www.moderndive.org, https://moderndive.org (using Google domains) and https://moderndive-release.netlify.com are all published from the `docs` folder on the `release` branch.

**Comment by ismayc** [comment]
I'm also going to uncheck the boxes above so we can just keep this as a running issue.

**Comment by ismayc** [comment]
You'll want to also copy the `previous_versions` folder over to the `docs` folder on the `releases` branch as well. I don't have the ftp login for that anymore.

**Comment by rudeboybert** [comment]
done; you can see the previous versions on moderndive.com

**Comment by rudeboybert** [comment]
While I copied `previous_versions` into `release` manually this time, if you look at 8ea074948fbf6e244289cdea108759ba961a8375 I copied all previous versions into a folder `previous_master` on master; I figured it was better to have all previous versions here too. 

From now on, whenever the book is built, `index.Rmd` will copy the contents of `previous_versions` to `docs/previous_versions`, and then instead of being located on `moderndive.com/previous_versions`, all previous versions will now be saved in a local folder.

**Comment by rudeboybert** [comment]
These steps are way out of date so I'm closing this issue
