### ISSUE TITLE
Make tables narrower to fit in PDF

### ISSUE THREAD

**Issue by ismayc** [moderndive/moderndive_book#63]
![screenshot 2018-08-13 14 25 27](https://user-images.githubusercontent.com/9215614/44059188-5ff4683c-9f05-11e8-8fa6-d0c107d39378.png)
![screenshot 2018-08-13 14 28 31](https://user-images.githubusercontent.com/9215614/44059189-601268a0-9f05-11e8-9bb6-29d4a4626684.png)

**Comment by ismayc** [comment]
![screenshot 2018-08-13 14 58 14](https://user-images.githubusercontent.com/9215614/44060386-64015bde-9f09-11e8-9544-3b63a085ca3e.png)

**Comment by ismayc** [comment]
![screenshot 2018-08-13 15 18 30](https://user-images.githubusercontent.com/9215614/44061178-287e1cfc-9f0c-11e8-921a-e09bfe9644c8.png)

**Comment by ismayc** [comment]
![screenshot 2018-08-13 15 30 24](https://user-images.githubusercontent.com/9215614/44061579-d733f4f0-9f0d-11e8-837d-fb7ba69acd47.png)

**Comment by ismayc** [comment]
![screenshot 2018-08-13 15 32 22](https://user-images.githubusercontent.com/9215614/44061633-1c0f754a-9f0e-11e8-9fff-e2702cba5d56.png)

**Comment by ismayc** [comment]
![screenshot 2018-08-13 15 34 04](https://user-images.githubusercontent.com/9215614/44061781-aae477ca-9f0e-11e8-9a51-ba7262bdd835.png)

**Comment by rudeboybert** [comment]
I'm going to assume this addressed in #161.
