### ISSUE TITLE
Fix equation formatting in Chapters 6 and 7

### ISSUE THREAD

**Issue by ismayc** [moderndive/moderndive_book#65]
![screenshot 2018-08-13 15 22 20](https://user-images.githubusercontent.com/9215614/44061312-b2537300-9f0c-11e8-8df3-4626dc8d5e0e.png)

![screenshot 2018-08-13 15 22 51](https://user-images.githubusercontent.com/9215614/44061321-c2c6aed2-9f0c-11e8-8473-1d9e7ae3235a.png)

**Comment by ismayc** [comment]
![screenshot 2018-08-13 15 35 58](https://user-images.githubusercontent.com/9215614/44061773-9fec4dd4-9f0e-11e8-83d5-b57cd2bd0027.png)

**Comment by ismayc** [comment]
![screenshot 2018-08-13 15 37 02](https://user-images.githubusercontent.com/9215614/44061821-c91738c2-9f0e-11e8-95c6-7080d28127a5.png)

**Comment by rudeboybert** [comment]
Easy peasy fix in 289ced680573c617e169ed18861022ce660bd8f2! Good old [StackOverflow](https://tex.stackexchange.com/questions/26637/how-do-you-get-mathbb1-to-work-characteristic-function-of-a-set) to the rescue!

**Comment by rudeboybert** [comment]
Killed this issue just 9 days short of its first birthday!
