### ISSUE TITLE
Show missing values as NA in PDF

### ISSUE THREAD

**Issue by ismayc** [moderndive/moderndive_book#66]
Can't get `options(knitr.kable.NA = 'NA')`or just omitting it  to work which should print `NA` as default in a PDF.

![screenshot 2018-08-14 17 02 21](https://user-images.githubusercontent.com/9215614/44124830-ff4bd85a-9fe3-11e8-9feb-7228170ce461.png)

**Comment by rudeboybert** [comment]
@ismayc Fixed by outputting default R output instead of kable table. I think we should only output to `knitr::kable()` selectively, for example when the presentation cleanliness of the result is important.
