### ISSUE TITLE
Add tactile_shovel1 dataset to package

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/moderndive_book#67]
@smetzer180 found in [9.6 EXAMPLE: One proportion](https://moderndive.com/9-confidence-intervals.html#one-prop-ci) we say the `tactile_shovel1` dataframe is included in `moderndive` package, but it isn't (we manually create it). At the very least in short term show code that manually creates this, in medium term add to `moderndive` package.

**Comment by ismayc** [comment]
Seems simple enough to just add it to the package, right?

**Comment by rudeboybert** [comment]
yeah, will do later. However, I'd rather have a dataframe name that didn't have a number appended and didn't want to go thru the agony of choosing a variable name right now 
![39195300_2020836437968637_7637633831582826496_n](https://user-images.githubusercontent.com/4574203/44683151-6fb47c80-aa13-11e8-9f9a-5c0aacab4bea.png)

**Comment by rudeboybert** [comment]
Added to `moderndive` package [here](https://github.com/moderndive/moderndive/commit/337db6da01773ef6f27902dbc6f559cf3fe98863) and renamed as `bowl_sample_1`.
