### ISSUE TITLE
Clarify t-test formula

### ISSUE THREAD

**Issue by apreshill** [moderndive/moderndive_book#69]
Hi,

After teaching this past quarter, I realized the formula given for the t-test needs clarification. _(I know you guys obviously know the difference, but I found myself wishing for more narrative around the formula provided in the text.)_ 

The formula given is:

$$T =\dfrac{ (\bar{x}_1 - \bar{x}_2) - (\mu_1 - \mu_2)}{ \sqrt{\dfrac{{s_1}^2}{n_1} + \dfrac{{s_2}^2}{n_2}}  }$$

![screen shot 2018-09-13 at 10 08 15 am](https://user-images.githubusercontent.com/12160301/45503847-f5873600-b73c-11e8-9824-27ea42480aa6.png)

But what is not said is that this the formula for Welch's t-test, where `var.equal = FALSE`:

![screen shot 2018-09-13 at 10 15 06 am](https://user-images.githubusercontent.com/12160301/45504162-f2407a00-b73d-11e8-8365-78470796a2cc.png)

The modified degrees of freedom would need to be clarified here as you can't use the formula given and actually do the t-test by hand without that too (and when teaching, helps students understand why all of a sudden the df can have decimals):

![screen shot 2018-09-13 at 10 15 49 am](https://user-images.githubusercontent.com/12160301/45504182-05534a00-b73e-11e8-842f-50a869abcfa9.png)

The t-test formula for `var.equal = TRUE` (in all its pooled SE glory) is [here](https://ohsu-conj620.netlify.com/slides/cm035.html#5):

![screen shot 2018-09-13 at 10 14 18 am](https://user-images.githubusercontent.com/12160301/45504109-d046f780-b73d-11e8-856a-9ff6fbdce5f5.png)

If you want an easy copy/paste, the formulas are in this [raw Rmd](https://raw.githubusercontent.com/apreshill/ohsu-basic-stats/master/slides/cm035.Rmd).

Again thanks for the awesome text- I really enjoyed teaching with it this past quarter!

Alison

**Comment by ismayc** [comment]
`var.equal = TRUE` is evil, but we should probably at the very least add this explanation to the Appendix and add a link in the chapter as well. Thanks, @apreshill!

**Comment by apreshill** [comment]
Yea you are not wrong! I prefer that as the default for sure- I think providing the df formula in the chapter would help, because we were at a point where we trying to calculate p- and critical t values using `pt` and `qt`, so it required more class time devoted to formulas than is enjoyable ;)

**Comment by ismayc** [comment]
Formula for `df` in the book instead of a link to the appendix? But it's so ugly... @rudeboybert, what do you think?

**Comment by rudeboybert** [comment]
I'd rather push that back to the appendix, but do a careful exposition there.

**Comment by rudeboybert** [comment]
Hey @apreshill, thanks for filling! We addressed this in #157, specifically by adding a section [10.6.1 Theory-based hypothesis tests](https://moderndive.netlify.com/10-hypothesis-testing.html#theory-hypo) that involves two-sample t-test. We only do the unequal var test and say "It can be mathematically proven that T follows a  t-distribution with degrees of freedom 'roughly equal' to df = n1 + n2 -2" and only link to the [actual df formula](https://en.wikipedia.org/wiki/Student%27s_t-test#Equal_or_unequal_sample_sizes,_unequal_variances). 

Thanks again for your help and support!
